---
- name: Scenario 1
  hosts: cloud_apic
  connection: local
  gather_facts: no

  tasks:
    - name: Import info from yml file
      include_vars:
        file: scenario-1-info.yml
        name: this

    - name: Create VLAN Pool 
      aci_vlan_pool:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no # yes
        pool: "{{ item.vlan_pool }}"
        pool_allocation_mode: "{{ item.vlan_pool_allocation_mode }}"
        state: present
      with_items: "{{ this.VLANs }}"
      register: print_output
    - debug: var=print_output

    - name: Add VLANs to the pool
      aci_encap_pool_range:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no # yes
        pool: "{{ item.vlan_pool }}"
        pool_type: "{{ item.vlan_pool_type }}"
        pool_allocation_mode: "{{ item.vlan_pool_allocation_mode }}"
        range_name: "{{ item.vlan_pool }}"
        range_start: "{{ item.vlan_pool_range_start }}"
        range_end: "{{ item.vlan_pool_range_end }}"
        allocation_mode: "{{ item.vlan_allocation_mode }}"
        state: present
      with_items: "{{ this.VLANs }}"
      register: print_output
    - debug: var=print_output

    - name: Create Physical domain
      aci_domain:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no # yes
        domain: "{{ item.domain }}"
        domain_type: "{{ item.domain_type }}"
        state: present
      with_items: "{{ this.Domains }}"
      register: print_output
    - debug: var=print_output

    - name: Associate domain to pool
      aci_domain_to_vlan_pool:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no # yes
        domain: "{{ item.0.domain }}"
        domain_type: "{{ item.0.domain_type }}"
        pool: "{{ item.1.vlan_pool }}"
        pool_allocation_mode: "{{ item.1.vlan_pool_allocation_mode }}"
        state: present
      with_nested:
      - "{{ this.Domains }}"
      - "{{ this.VLANs }}"
      register: print_output
    - debug: var=print_output

    - name: Create an AEP
      aci_aep:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no # yes
        aep: "{{ item.aep }}"
        description: "{{ item.aep_desc }}"
        state: present
      with_items: "{{ this.AEPs }}"
      register: print_output
    - debug: var=print_output

    - name: Associate AEP to phys domain
      aci_aep_to_domain: &binding_present
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no # yes
        aep: "{{ item.0.aep }}"
        domain: "{{ item.1.domain }}"
        domain_type: "{{ item.1.domain_type }}"
        state: present
      with_nested:
      - "{{ this.AEPs }}"
      - "{{ this.Domains }}"
      register: print_output
    - debug: var=print_output